"""added is_active column

Revision ID: 228a62037a87
Revises: c59b6b2dfe1a
Create Date: 2025-11-03 11:32:20.986509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228a62037a87'
down_revision = 'c59b6b2dfe1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slides', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
